#!/usr/bin/env bash

if [ -S "/Users/$(id -unr)/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock" ]; then
  export SSH_AUTH_SOCK="/Users/$(id -unr)/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock"
fi
