#!/usr/bin/env bash

if ! _have claude; then
  return
fi

askr() {
  local dir="/tmp/claude-non-interactive"
  mkdir -p "$dir"
  (cd "$dir" && claude --model haiku -p --no-session-persistence "$@")
}

ask() {
  local dir="/tmp/claude-non-interactive"
  mkdir -p "$dir"
  (cd "$dir" && claude --model haiku -p "$@")
}

askk() {
  local dir="/tmp/claude-non-interactive"
  mkdir -p "$dir"
  (cd "$dir" && claude --model haiku -p --continue "$@")
}
