#!/usr/bin/env bash

if ! _have fzf; then
  return
fi

eval "$(fzf --bash)"

if [[ ! "$PATH" == "*/${HOMEBREW_PREFIX}/opt/fzf/bin*" ]]; then
  export PATH="${PATH:+${PATH}:}/${HOMEBREW_PREFIX}/opt/fzf/bin"
fi

eval "$(fzf --bash)"

test -e "${XDG_CONFIG_HOME}/fzf/git/fzf-git.sh" && source "${XDG_CONFIG_HOME}/fzf/git/fzf-git.sh"
test -e "${XDG_CONFIG_HOME}/fzf/docker/docker-fzf" && source "${XDG_CONFIG_HOME}/fzf/docker/docker-fzf"
