#!/usr/bin/env bash

brewpath="/opt/homebrew/bin/brew"

[[ ! -x "$brewpath" ]] && return 2>/dev/null

export HOMEBREW_NO_AUTO_UPDATE=1

eval "$("$brewpath" shellenv)"

if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
  source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
else
  for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
    [[ -r "$COMPLETION" ]] && source "$COMPLETION"
  done
fi
