#!/usr/bin/env bash

javapath="${HOMEBREW_PREFIX}/opt/openjdk@17/bin"

[[ ! -d "$javapath" ]] && return 2>/dev/null

export PATH="${javapath}:$PATH"
export JAVA_HOME="${HOMEBREW_PREFIX}/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"

