#!/usr/bin/env bash

if ! _have fzf; then
  return
fi

if ! _have rg; then
  return
fi

if ! _have bat; then
  return
fi

rfv() {
  rg --color=always --line-number --no-heading --smart-case "${*:-}" |
  fzf --ansi \
  --color "hl:-1:underline,hl+:-1:underline:reverse" \
  --delimiter : \
  --preview 'bat --color=always {1} --highlight-line {2}' \
  --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
  --bind 'enter:become(nvim {1} +{2})'
}
