set-option -g default-shell "${SHELL}"

set-option -g default-terminal "tmux-256color"
set-option -g terminal-overrides ",*256col*:Tc:RGB"

set-option -g focus-events on

set-option -g mouse on

set-option -g status-keys vi
set-window-option -g mode-keys vi

set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g detach-on-destroy off

set-option -g history-limit 50000

set-option -g window-style 'fg=terminal,bg=terminal'
set-option -g window-active-style 'fg=terminal,bg=terminal'

set-option -g pane-border-style "bg=terminal fg=terminal"
set-option -g pane-active-border-style "bg=terminal fg=terminal"

set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# clipboard
# macos
#bind-key -T copy-mode-vi Y send -X copy-pipe "pbcopy"
#bind-key P run "pbpaste | tmux load-buffer - && tmux paste-buffer"
# windows
#bind-key -T copy-mode-vi Y send -X copy-pipe "clip.exe"
#bind-key P run "pbpaste | tmux load-buffer - && tmux paste-buffer"
# linux
#bind-key -T copy-mode-vi Y send -X copy-pipe "xclip -i -sel clipboard"

bind r source ~/.config/tmux/tmux.conf\; display ".tmux.conf reloaded!"

bind m set-option monitor-activity
bind y set-option synchronize-panes

bind-key F set-option status

# open new window/pane in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# vi keys to resize
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 2
bind -r C-l resize-pane -R 2

bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# application shortcut
bind v new-window -c "#{pane_current_path}" nvim
bind f new-window "$XDG_CONFIG_HOME/tmux/scripts/fzf-cd.sh"

bind g display-popup -E -w 70% -h 90% -x C -y C -d "#{pane_current_path}" "tmux new-session -A -s scratch"
bind G display-popup -E -d "#{pane_current_path}"
bind C-m select-pane -m
bind C-p last-pane
bind C-o last-window

run "$XDG_CONFIG_HOME/tmux/plugins/catppuccin/catppuccin.tmux"

# statusbar color
set-option -g status-style bg=terminal,fg=terminal
set-option -g status-justify "centre"
set-option -g status-left ""
set-option -g status-right ""
set-window-option -g window-status-format "#[bg=default,fg=color240,bold]#W"
set-window-option -g window-status-current-format "#[bg=default,fg=default,bold]#W"

# If running inside tmux ($TMUX is set), then change the status line to red
%if #{TMUX} set -g status-bg red %endif
